blank_issues_enabled: false
contact_links:
  - name: Report a security vulnerability
    url: https://aka.ms/security.md
    about: Report vulnerabilities privately through the Microsoft Security Response Center.

